[package]
name = "lepton_rs"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Device driver for the flir-Lepton camera module"

[dependencies]
embedded-hal = "1.0.0"
log = "0.4.29"
